# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sensor_pb2 as sensor__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sensor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorServiceStub(object):
    """*
    SensorService -- gRPC Service untuk gateway sensor

    Menyediakan 4 jenis komunikasi gRPC:
    1. Unary         : request-response sederhana (1 kirim, 1 balas)
    2. Client Stream : client kirim banyak data, server balas 1 rangkuman
    3. Server Stream : client kirim 1 request, server balas data berkala
    4. Bidirectional : client dan server saling kirim secara real-time
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSensorData = channel.unary_unary(
                '/iot.SensorService/SendSensorData',
                request_serializer=sensor__pb2.SensorRequest.SerializeToString,
                response_deserializer=sensor__pb2.SensorResponse.FromString,
                _registered_method=True)
        self.StreamSensorData = channel.stream_unary(
                '/iot.SensorService/StreamSensorData',
                request_serializer=sensor__pb2.SensorRequest.SerializeToString,
                response_deserializer=sensor__pb2.SensorResponse.FromString,
                _registered_method=True)
        self.MonitorSensor = channel.unary_stream(
                '/iot.SensorService/MonitorSensor',
                request_serializer=sensor__pb2.SensorRequest.SerializeToString,
                response_deserializer=sensor__pb2.SensorResponse.FromString,
                _registered_method=True)
        self.InteractiveSensor = channel.stream_stream(
                '/iot.SensorService/InteractiveSensor',
                request_serializer=sensor__pb2.SensorRequest.SerializeToString,
                response_deserializer=sensor__pb2.SensorResponse.FromString,
                _registered_method=True)


class SensorServiceServicer(object):
    """*
    SensorService -- gRPC Service untuk gateway sensor

    Menyediakan 4 jenis komunikasi gRPC:
    1. Unary         : request-response sederhana (1 kirim, 1 balas)
    2. Client Stream : client kirim banyak data, server balas 1 rangkuman
    3. Server Stream : client kirim 1 request, server balas data berkala
    4. Bidirectional : client dan server saling kirim secara real-time
    """

    def SendSensorData(self, request, context):
        """1. Unary RPC: Kirim satu data sensor, terima satu respon
        Cocok untuk: pengiriman data sensor satu per satu
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSensorData(self, request_iterator, context):
        """2. Client Streaming: Kirim banyak data sekaligus, terima satu ringkasan
        Cocok untuk: batch upload data sensor dari buffer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorSensor(self, request, context):
        """3. Server Streaming: Kirim satu perintah monitor, terima data kontinu
        Cocok untuk: real-time monitoring satu sensor tertentu
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InteractiveSensor(self, request_iterator, context):
        """4. Bidirectional Streaming: Komunikasi dua arah real-time
        Cocok untuk: sesi interaktif (kirim data, langsung dapat response)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSensorData,
                    request_deserializer=sensor__pb2.SensorRequest.FromString,
                    response_serializer=sensor__pb2.SensorResponse.SerializeToString,
            ),
            'StreamSensorData': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamSensorData,
                    request_deserializer=sensor__pb2.SensorRequest.FromString,
                    response_serializer=sensor__pb2.SensorResponse.SerializeToString,
            ),
            'MonitorSensor': grpc.unary_stream_rpc_method_handler(
                    servicer.MonitorSensor,
                    request_deserializer=sensor__pb2.SensorRequest.FromString,
                    response_serializer=sensor__pb2.SensorResponse.SerializeToString,
            ),
            'InteractiveSensor': grpc.stream_stream_rpc_method_handler(
                    servicer.InteractiveSensor,
                    request_deserializer=sensor__pb2.SensorRequest.FromString,
                    response_serializer=sensor__pb2.SensorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iot.SensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('iot.SensorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensorService(object):
    """*
    SensorService -- gRPC Service untuk gateway sensor

    Menyediakan 4 jenis komunikasi gRPC:
    1. Unary         : request-response sederhana (1 kirim, 1 balas)
    2. Client Stream : client kirim banyak data, server balas 1 rangkuman
    3. Server Stream : client kirim 1 request, server balas data berkala
    4. Bidirectional : client dan server saling kirim secara real-time
    """

    @staticmethod
    def SendSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/iot.SensorService/SendSensorData',
            sensor__pb2.SensorRequest.SerializeToString,
            sensor__pb2.SensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSensorData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/iot.SensorService/StreamSensorData',
            sensor__pb2.SensorRequest.SerializeToString,
            sensor__pb2.SensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/iot.SensorService/MonitorSensor',
            sensor__pb2.SensorRequest.SerializeToString,
            sensor__pb2.SensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InteractiveSensor(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/iot.SensorService/InteractiveSensor',
            sensor__pb2.SensorRequest.SerializeToString,
            sensor__pb2.SensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
