# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x03iot\"\xae\x01\n\rSensorRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12\x13\n\x0bsensor_name\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\x12\x10\n\x08humidity\x18\x04 \x01(\x01\x12\x10\n\x08pressure\x18\x05 \x01(\x01\x12\x17\n\x0flight_intensity\x18\x06 \x01(\x01\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x12\x10\n\x08location\x18\x08 \x01(\t\"O\n\x0eSensorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1b\n\x13processed_timestamp\x18\x03 \x01(\x03\x32\x87\x02\n\rSensorService\x12\x39\n\x0eSendSensorData\x12\x12.iot.SensorRequest\x1a\x13.iot.SensorResponse\x12=\n\x10StreamSensorData\x12\x12.iot.SensorRequest\x1a\x13.iot.SensorResponse(\x01\x12:\n\rMonitorSensor\x12\x12.iot.SensorRequest\x1a\x13.iot.SensorResponse0\x01\x12@\n\x11InteractiveSensor\x12\x12.iot.SensorRequest\x1a\x13.iot.SensorResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORREQUEST']._serialized_start=22
  _globals['_SENSORREQUEST']._serialized_end=196
  _globals['_SENSORRESPONSE']._serialized_start=198
  _globals['_SENSORRESPONSE']._serialized_end=277
  _globals['_SENSORSERVICE']._serialized_start=280
  _globals['_SENSORSERVICE']._serialized_end=543
# @@protoc_insertion_point(module_scope)
