#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <FILE_NAME>"
    echo "Example: $0 idl/SensorData/SensorData"
    exit 1
fi

IDL_INPUT_PATH="$1"
IDL_DIR=$(dirname "$IDL_INPUT_PATH")
IDL_BASE=$(basename "$IDL_INPUT_PATH")
IDL_FILE_NAME="${IDL_BASE}.idl"
TYPE_SUPPORT_FILE_NAME="${IDL_BASE}TypeSupport.idl"

# Run from IDL directory so includes resolve correctly
cd "$IDL_DIR" || exit 1

tao_idl -I "$DDS_ROOT" -I . -Sa -St -Sm -Sci -in --idl-version 4 --unknown-annotations ignore "$IDL_FILE_NAME"
opendds_idl -I . -Gxtypes-complete "$IDL_FILE_NAME"
tao_idl -I "$DDS_ROOT" -I . -Sa -St -Sm -Sci -in --idl-version 4 --unknown-annotations ignore "$TYPE_SUPPORT_FILE_NAME"

echo "Execution completed."
