// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "SensorDataTypeSupportC.h"
#include "tao/CDR.h"
#include "cstring"
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Messengger::MessageTypeSupport.

Messengger::MessageTypeSupport_ptr
TAO::Objref_Traits<Messengger::MessageTypeSupport>::duplicate (Messengger::MessageTypeSupport_ptr p)
{
  return Messengger::MessageTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Messengger::MessageTypeSupport>::release (Messengger::MessageTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Messengger::MessageTypeSupport_ptr
TAO::Objref_Traits<Messengger::MessageTypeSupport>::nil ()
{
  return Messengger::MessageTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Messengger::MessageTypeSupport>::marshal (const Messengger::MessageTypeSupport_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Messengger::MessageTypeSupport::MessageTypeSupport ()
{}Messengger::MessageTypeSupport_ptr
Messengger::MessageTypeSupport::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return MessageTypeSupport::_duplicate (
      dynamic_cast<MessageTypeSupport_ptr> (_tao_objref));
}

Messengger::MessageTypeSupport_ptr
Messengger::MessageTypeSupport::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return MessageTypeSupport::_duplicate (
      dynamic_cast<MessageTypeSupport_ptr> (_tao_objref));
}

Messengger::MessageTypeSupport_ptr
Messengger::MessageTypeSupport::_nil ()
{
  return nullptr;
}

Messengger::MessageTypeSupport_ptr
Messengger::MessageTypeSupport::_duplicate (MessageTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Messengger::MessageTypeSupport::_tao_release (MessageTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Messengger::MessageTypeSupport::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/TypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:Messengger/MessageTypeSupport:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Messengger::MessageTypeSupport::_interface_repository_id () const
{
  return "IDL:Messengger/MessageTypeSupport:1.0";
}

::CORBA::Boolean
Messengger::MessageTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Messengger::MessageDataWriter.

Messengger::MessageDataWriter_ptr
TAO::Objref_Traits<Messengger::MessageDataWriter>::duplicate (Messengger::MessageDataWriter_ptr p)
{
  return Messengger::MessageDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Messengger::MessageDataWriter>::release (Messengger::MessageDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Messengger::MessageDataWriter_ptr
TAO::Objref_Traits<Messengger::MessageDataWriter>::nil ()
{
  return Messengger::MessageDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Messengger::MessageDataWriter>::marshal (const Messengger::MessageDataWriter_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Messengger::MessageDataWriter::MessageDataWriter ()
{}Messengger::MessageDataWriter_ptr
Messengger::MessageDataWriter::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return MessageDataWriter::_duplicate (
      dynamic_cast<MessageDataWriter_ptr> (_tao_objref));
}

Messengger::MessageDataWriter_ptr
Messengger::MessageDataWriter::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return MessageDataWriter::_duplicate (
      dynamic_cast<MessageDataWriter_ptr> (_tao_objref));
}

Messengger::MessageDataWriter_ptr
Messengger::MessageDataWriter::_nil ()
{
  return nullptr;
}

Messengger::MessageDataWriter_ptr
Messengger::MessageDataWriter::_duplicate (MessageDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Messengger::MessageDataWriter::_tao_release (MessageDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Messengger::MessageDataWriter::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:Messengger/MessageDataWriter:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Messengger::MessageDataWriter::_interface_repository_id () const
{
  return "IDL:Messengger/MessageDataWriter:1.0";
}

::CORBA::Boolean
Messengger::MessageDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /opt/odds3291-java/OpenDDS-3.29.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Messengger::MessageDataReader.

Messengger::MessageDataReader_ptr
TAO::Objref_Traits<Messengger::MessageDataReader>::duplicate (Messengger::MessageDataReader_ptr p)
{
  return Messengger::MessageDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Messengger::MessageDataReader>::release (Messengger::MessageDataReader_ptr p)
{
  ::CORBA::release (p);
}

Messengger::MessageDataReader_ptr
TAO::Objref_Traits<Messengger::MessageDataReader>::nil ()
{
  return Messengger::MessageDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Messengger::MessageDataReader>::marshal (const Messengger::MessageDataReader_ptr p,TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Messengger::MessageDataReader::MessageDataReader ()
{}Messengger::MessageDataReader_ptr
Messengger::MessageDataReader::_narrow (::CORBA::Object_ptr _tao_objref)
{
  return MessageDataReader::_duplicate (
      dynamic_cast<MessageDataReader_ptr> (_tao_objref));
}

Messengger::MessageDataReader_ptr
Messengger::MessageDataReader::_unchecked_narrow (::CORBA::Object_ptr _tao_objref)
{
  return MessageDataReader::_duplicate (
      dynamic_cast<MessageDataReader_ptr> (_tao_objref));
}

Messengger::MessageDataReader_ptr
Messengger::MessageDataReader::_nil ()
{
  return nullptr;
}

Messengger::MessageDataReader_ptr
Messengger::MessageDataReader::_duplicate (MessageDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Messengger::MessageDataReader::_tao_release (MessageDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Messengger::MessageDataReader::_is_a (const char *value)
{
  if (
      std::strcmp (value, "IDL:DDS/Entity:1.0") == 0 ||
      std::strcmp (value, "IDL:DDS/DataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:OpenDDS/DCPS/DataReaderEx:1.0") == 0 ||
      std::strcmp (value, "IDL:Messengger/MessageDataReader:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/LocalObject:1.0") == 0 ||
      std::strcmp (value, "IDL:omg.org/CORBA/Object:1.0") == 0
      )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Messengger::MessageDataReader::_interface_repository_id () const
{
  return "IDL:Messengger/MessageDataReader:1.0";
}

::CORBA::Boolean
Messengger::MessageDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

