/* Generated by opendds_idl version 3.29.1 (ACE version 8.0.0) running on input file SensorData.idl */
#include "SensorDataTypeSupportImpl.h"

#include <cstring>
#include <stdexcept>
#include "dds/DCPS/BuiltInTopicUtils.h"
#include "dds/DCPS/ContentFilteredTopicImpl.h"
#include "dds/DCPS/DataReaderImpl_T.h"
#include "dds/DCPS/DataWriterImpl_T.h"
#include "dds/DCPS/FilterEvaluator.h"
#include "dds/DCPS/MultiTopicDataReader_T.h"
#include "dds/DCPS/PoolAllocator.h"
#include "dds/DCPS/PublicationInstance.h"
#include "dds/DCPS/PublisherImpl.h"
#include "dds/DCPS/Qos_Helper.h"
#include "dds/DCPS/RakeData.h"
#include "dds/DCPS/RakeResults_T.h"
#include "dds/DCPS/ReceivedDataElementList.h"
#include "dds/DCPS/Registered_Data_Types.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/SubscriberImpl.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/XTypes/TypeObject.h"
#include "dds/DCPS/debug.h"
#include "dds/DdsDcpsDomainC.h"
#include "dds/DCPS/JsonValueReader.h"
#include "dds/DCPS/JsonValueWriter.h"

#ifdef OPENDDS_IDL_FILE_SPECIFIC
#  undef OPENDDS_IDL_FILE_SPECIFIC
#endif
#define OPENDDS_IDL_FILE_SPECIFIC(base, index) opendds_idl_generated_sensordatatypesupportimpl_cpp_bf8efm##_##base##index



/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Messengger */



/* Begin STRUCT: Message */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<Messengger_Message_xtag>()
{
  static XTypes::TypeIdentifier ti;
  ACE_GUARD_RETURN(ACE_Thread_Mutex, guard, TheServiceParticipant->get_static_xtypes_lock(), ti);
  if (ti.kind() == XTypes::TK_NONE) {
    ti = XTypes::TypeIdentifier(XTypes::EK_MINIMAL, XTypes::EquivalenceHashWrapper(21, 42, 3, 79, 102, 114, 218, 239, 105, 167, 227, 124, 201, 240));
  }
  return ti;
}

static const XTypes::TypeMap& OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map, 0)();
static const XTypes::TypeMap& OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map, 0)();
template<> const XTypes::TypeMap& getMinimalTypeMap<Messengger_Message_xtag>()
{
  return OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map, 0)();
}

template<> const XTypes::TypeIdentifier& getCompleteTypeIdentifier<Messengger_Message_xtag>()
{
  static XTypes::TypeIdentifier ti;
  ACE_GUARD_RETURN(ACE_Thread_Mutex, guard, TheServiceParticipant->get_static_xtypes_lock(), ti);
  if (ti.kind() == XTypes::TK_NONE) {
    ti = XTypes::TypeIdentifier(XTypes::EK_COMPLETE, XTypes::EquivalenceHashWrapper(3, 125, 222, 30, 113, 7, 154, 203, 17, 121, 124, 49, 17, 248));
  }
  return ti;
}

template<> const XTypes::TypeMap& getCompleteTypeMap<Messengger_Message_xtag>()
{
  return OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map, 0)();
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::Messengger::Message& value)
{
  ACE_UNUSED_ARG(value_reader);
  ACE_UNUSED_ARG(value);
  static const ListMemberHelper::Pair pairs[] = {{"sensor_id",0},{"sensor_name",1},{"temperature",2},{"humidity",3},{"pressure",4},{"light_intensity",5},{"timestamp",6},{"location",7},{0,0}};
  ListMemberHelper helper(pairs);
  if (!value_reader.begin_struct(OpenDDS::DCPS::APPENDABLE)) return false;
  XTypes::MemberId member_id;
  while (value_reader.members_remaining()) {
    if (!value_reader.begin_struct_member(member_id, helper)) return false;
    switch (member_id) {
    case 0: {
      if (!value_reader.read_int32(value.sensor_id)) return false;
      break;
    }
    case 1: {
      {
        String x;
        if (!value_reader.read_string(x)) return false;
        value.sensor_name = x.c_str();
      }
      break;
    }
    case 2: {
      if (!value_reader.read_float64(value.temperature)) return false;
      break;
    }
    case 3: {
      if (!value_reader.read_float64(value.humidity)) return false;
      break;
    }
    case 4: {
      if (!value_reader.read_float64(value.pressure)) return false;
      break;
    }
    case 5: {
      if (!value_reader.read_float64(value.light_intensity)) return false;
      break;
    }
    case 6: {
      if (!value_reader.read_int64(value.timestamp)) return false;
      break;
    }
    case 7: {
      {
        String x;
        if (!value_reader.read_string(x)) return false;
        value.location = x.c_str();
      }
      break;
    }
    }
    if (!value_reader.end_struct_member()) return false;
  }
  if (!value_reader.end_struct()) return false;
  return true;
}

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::Messengger::Message>& value)
{
  ACE_UNUSED_ARG(value_reader);
  ACE_UNUSED_ARG(value);
  static const ListMemberHelper::Pair pairs[] = {{"sensor_id",0},{"sensor_name",1},{"temperature",2},{"humidity",3},{"pressure",4},{"light_intensity",5},{"timestamp",6},{"location",7},{0,0}};
  ListMemberHelper helper(pairs);
  if (!value_reader.begin_struct(OpenDDS::DCPS::APPENDABLE)) return false;
  XTypes::MemberId member_id;
  while (value_reader.members_remaining()) {
    if (!value_reader.begin_struct_member(member_id, helper)) return false;
    switch (member_id) {
    case 0: {
      if (!value_reader.read_int32(value.value.sensor_id)) return false;
      break;
    }
    case 1: {
      {
        String x;
        if (!value_reader.read_string(x)) return false;
        value.value.sensor_name = x.c_str();
      }
      break;
    }
    case 2: {
      if (!value_reader.read_float64(value.value.temperature)) return false;
      break;
    }
    case 3: {
      if (!value_reader.read_float64(value.value.humidity)) return false;
      break;
    }
    case 4: {
      if (!value_reader.read_float64(value.value.pressure)) return false;
      break;
    }
    case 5: {
      if (!value_reader.read_float64(value.value.light_intensity)) return false;
      break;
    }
    case 6: {
      if (!value_reader.read_int64(value.value.timestamp)) return false;
      break;
    }
    case 7: {
      {
        String x;
        if (!value_reader.read_string(x)) return false;
        value.value.location = x.c_str();
      }
      break;
    }
    }
    if (!value_reader.end_struct_member()) return false;
  }
  if (!value_reader.end_struct()) return false;
  return true;
}

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const KeyOnly< ::Messengger::Message>& value)
{
  ACE_UNUSED_ARG(value_reader);
  ACE_UNUSED_ARG(value);
  static const ListMemberHelper::Pair pairs[] = {{0,0}};
  ListMemberHelper helper(pairs);
  if (!value_reader.begin_struct(OpenDDS::DCPS::APPENDABLE)) return false;
  if (!value_reader.end_struct()) return false;
  return true;
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::Messengger::Message& value)
{
  ACE_UNUSED_ARG(value_writer);
  ACE_UNUSED_ARG(value);
  if (!value_writer.begin_struct(OpenDDS::DCPS::APPENDABLE)) {
    return false;
  }
  {
    MemberParam param(0, false, "sensor_id", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_int32(value.sensor_id)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(1, false, "sensor_name", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_string(value.sensor_name)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(2, false, "temperature", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_float64(value.temperature)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(3, false, "humidity", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_float64(value.humidity)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(4, false, "pressure", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_float64(value.pressure)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(5, false, "light_intensity", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_float64(value.light_intensity)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(6, false, "timestamp", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_int64(value.timestamp)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(7, false, "location", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_string(value.location)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  return value_writer.end_struct();
}

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::Messengger::Message>& value)
{
  ACE_UNUSED_ARG(value_writer);
  ACE_UNUSED_ARG(value);
  if (!value_writer.begin_struct(OpenDDS::DCPS::APPENDABLE)) {
    return false;
  }
  {
    MemberParam param(0, false, "sensor_id", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_int32(value.value.sensor_id)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(1, false, "sensor_name", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_string(value.value.sensor_name)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(2, false, "temperature", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_float64(value.value.temperature)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(3, false, "humidity", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_float64(value.value.humidity)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(4, false, "pressure", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_float64(value.value.pressure)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(5, false, "light_intensity", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_float64(value.value.light_intensity)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(6, false, "timestamp", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_int64(value.value.timestamp)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  {
    MemberParam param(7, false, "location", 0, true);
    if (!value_writer.begin_struct_member(param)) {
      return false;
    }
    if (param.present) {
      if (!value_writer.write_string(value.value.location)) {
        return false;
      }
    } else {
      value_writer.write_absent_value();
    }
    if (!value_writer.end_struct_member()) {
      return false;
    }
  }
  return value_writer.end_struct();
}

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const KeyOnly<const  ::Messengger::Message>& value)
{
  ACE_UNUSED_ARG(value_writer);
  ACE_UNUSED_ARG(value);
  if (!value_writer.begin_struct(OpenDDS::DCPS::APPENDABLE)) {
    return false;
  }
  return value_writer.end_struct();
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> void set_default( ::Messengger::Message& stru)
{
  ACE_UNUSED_ARG(stru);
  stru.sensor_id = 0;
  stru.sensor_name = "";
  stru.temperature = 0;
  stru.humidity = 0;
  stru.pressure = 0;
  stru.light_intensity = 0;
  stru.timestamp = 0;
  stru.location = "";
}

void serialized_size(const Encoding& encoding, size_t& size, const ::Messengger::Message& stru)
{
  ACE_UNUSED_ARG(encoding);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(stru);
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size_delimiter(encoding, size);
  }
  primitive_serialized_size(encoding, size, stru.sensor_id);
  primitive_serialized_size_ulong(encoding, size);
  size += ACE_OS::strlen(stru.sensor_name.in()) + 1;
  primitive_serialized_size(encoding, size, stru.temperature);
  primitive_serialized_size(encoding, size, stru.humidity);
  primitive_serialized_size(encoding, size, stru.pressure);
  primitive_serialized_size(encoding, size, stru.light_intensity);
  primitive_serialized_size(encoding, size, stru.timestamp);
  primitive_serialized_size_ulong(encoding, size);
  size += ACE_OS::strlen(stru.location.in()) + 1;
}

bool operator<<(Serializer& strm, const ::Messengger::Message& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size(encoding, total_size, stru);
    if (!strm.write_delimiter(total_size)) {
      return false;
    }
  }
  return (strm << stru.sensor_id)
    && (strm << stru.sensor_name.in())
    && (strm << stru.temperature)
    && (strm << stru.humidity)
    && (strm << stru.pressure)
    && (strm << stru.light_intensity)
    && (strm << stru.timestamp)
    && (strm << stru.location.in());
}

bool operator>>(Serializer& strm,  ::Messengger::Message& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  bool reached_end_of_struct = false;
  ACE_UNUSED_ARG(reached_end_of_struct);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    if (!strm.read_delimiter(total_size)) {
      return false;
    }
  }
  const size_t end_of_struct = strm.rpos() + total_size;

  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.sensor_id = 0;
  } else {
    if (!(strm >> stru.sensor_id)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.sensor_name = "";
  } else {
    if (!(strm >> stru.sensor_name.out())) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.temperature = 0;
  } else {
    if (!(strm >> stru.temperature)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.humidity = 0;
  } else {
    if (!(strm >> stru.humidity)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.pressure = 0;
  } else {
    if (!(strm >> stru.pressure)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.light_intensity = 0;
  } else {
    if (!(strm >> stru.light_intensity)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.timestamp = 0;
  } else {
    if (!(strm >> stru.timestamp)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.location = "";
  } else {
    if (!(strm >> stru.location.out())) {
      return false;
    }
  }
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() < end_of_struct) {
    strm.skip(end_of_struct - strm.rpos());
  }
  return true;
}

void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::Messengger::Message>& stru)
{
  ACE_UNUSED_ARG(encoding);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(stru);
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size_delimiter(encoding, size);
  }
  primitive_serialized_size(encoding, size, stru.value.sensor_id);
  primitive_serialized_size_ulong(encoding, size);
  size += ACE_OS::strlen(stru.value.sensor_name.in()) + 1;
  primitive_serialized_size(encoding, size, stru.value.temperature);
  primitive_serialized_size(encoding, size, stru.value.humidity);
  primitive_serialized_size(encoding, size, stru.value.pressure);
  primitive_serialized_size(encoding, size, stru.value.light_intensity);
  primitive_serialized_size(encoding, size, stru.value.timestamp);
  primitive_serialized_size_ulong(encoding, size);
  size += ACE_OS::strlen(stru.value.location.in()) + 1;
}

bool operator<<(Serializer& strm, const NestedKeyOnly<const ::Messengger::Message>& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size(encoding, total_size, stru);
    if (!strm.write_delimiter(total_size)) {
      return false;
    }
  }
  return (strm << stru.value.sensor_id)
    && (strm << stru.value.sensor_name.in())
    && (strm << stru.value.temperature)
    && (strm << stru.value.humidity)
    && (strm << stru.value.pressure)
    && (strm << stru.value.light_intensity)
    && (strm << stru.value.timestamp)
    && (strm << stru.value.location.in());
}

bool operator>>(Serializer& strm, const NestedKeyOnly< ::Messengger::Message>& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  bool reached_end_of_struct = false;
  ACE_UNUSED_ARG(reached_end_of_struct);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    if (!strm.read_delimiter(total_size)) {
      return false;
    }
  }
  const size_t end_of_struct = strm.rpos() + total_size;

  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.sensor_id = 0;
  } else {
    if (!(strm >> stru.value.sensor_id)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.sensor_name = "";
  } else {
    if (!(strm >> stru.value.sensor_name.out())) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.temperature = 0;
  } else {
    if (!(strm >> stru.value.temperature)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.humidity = 0;
  } else {
    if (!(strm >> stru.value.humidity)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.pressure = 0;
  } else {
    if (!(strm >> stru.value.pressure)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.light_intensity = 0;
  } else {
    if (!(strm >> stru.value.light_intensity)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.timestamp = 0;
  } else {
    if (!(strm >> stru.value.timestamp)) {
      return false;
    }
  }
  reached_end_of_struct |= (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() >= end_of_struct);
  if (reached_end_of_struct) {
    stru.value.location = "";
  } else {
    if (!(strm >> stru.value.location.out())) {
      return false;
    }
  }
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() < end_of_struct) {
    strm.skip(end_of_struct - strm.rpos());
  }
  return true;
}

void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const ::Messengger::Message>& stru)
{
  ACE_UNUSED_ARG(encoding);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(stru);
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size_delimiter(encoding, size);
  }
}

bool operator<<(Serializer& strm, const KeyOnly<const ::Messengger::Message>& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    serialized_size(encoding, total_size, stru);
    if (!strm.write_delimiter(total_size)) {
      return false;
    }
  }
  return true;
}

bool operator>>(Serializer& strm, const KeyOnly< ::Messengger::Message>& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  const Encoding& encoding = strm.encoding();
  ACE_UNUSED_ARG(encoding);
  bool reached_end_of_struct = false;
  ACE_UNUSED_ARG(reached_end_of_struct);
  size_t total_size = 0;
  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
    if (!strm.read_delimiter(total_size)) {
      return false;
    }
  }
  const size_t end_of_struct = strm.rpos() + total_size;

  if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2 && strm.rpos() < end_of_struct) {
    strm.skip(end_of_struct - strm.rpos());
  }
  return true;
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
bool DDSTraits< ::Messengger::Message>::is_key(const char* field)
{
  ACE_UNUSED_ARG(field);
  return false;
}
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL

namespace Messengger {
::DDS::DataWriter_ptr MessageTypeSupportImpl::create_datawriter()
{
  typedef OpenDDS::DCPS::DataWriterImpl_T<Message> DataWriterImplType;
  ::DDS::DataWriter_ptr writer_impl = ::DDS::DataWriter::_nil();
  ACE_NEW_NORETURN(writer_impl,
                   DataWriterImplType());
  return writer_impl;
}

::DDS::DataReader_ptr MessageTypeSupportImpl::create_datareader()
{
  typedef OpenDDS::DCPS::DataReaderImpl_T<Message> DataReaderImplType;
  ::DDS::DataReader_ptr reader_impl = ::DDS::DataReader::_nil();
  ACE_NEW_NORETURN(reader_impl,
                   DataReaderImplType());
  return reader_impl;
}

#ifndef OPENDDS_NO_MULTI_TOPIC
::DDS::DataReader_ptr MessageTypeSupportImpl::create_multitopic_datareader()
{
  typedef OpenDDS::DCPS::DataReaderImpl_T<Message> DataReaderImplType;
  typedef OpenDDS::DCPS::MultiTopicDataReader_T<Message, DataReaderImplType> MultiTopicDataReaderImplType;
  ::DDS::DataReader_ptr multitopic_reader_impl = ::DDS::DataReader::_nil();
  ACE_NEW_NORETURN(multitopic_reader_impl,
                   MultiTopicDataReaderImplType());
  return multitopic_reader_impl;
}
#endif /* !OPENDDS_NO_MULTI_TOPIC */

#ifndef OPENDDS_SAFETY_PROFILE
Message* MessageTypeSupportImpl::create_sample(::DDS::DynamicData_ptr src)
{
  Message* value = new Message;
  const ::DDS::ReturnCode_t rc = OpenDDS::DCPS::TypeSupportImpl_T<Message>::create_sample_rc(*value, src);
  if (rc != ::DDS::RETCODE_OK && OpenDDS::DCPS::log_level >= OpenDDS::DCPS::LogLevel::Warning) {
    ACE_ERROR((LM_WARNING, "(%P|%t) WARNING: MessageTypeSupportImpl::create_sample: "
      "create_sample_rc failed: %C\n", OpenDDS::DCPS::retcode_to_string(rc)));
  }
  return value;
}
#endif

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
const OpenDDS::DCPS::MetaStruct& MessageTypeSupportImpl::getMetaStructForType() const
{
  return OpenDDS::DCPS::getMetaStruct<Message>();
}
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

namespace {
  OpenDDS::DCPS::TypeSupportInitializer<MessageTypeSupportImpl> ts_init_Messengger_Message;
}

const OpenDDS::XTypes::TypeIdentifier& MessageTypeSupportImpl::getMinimalTypeIdentifier() const
{
  return OpenDDS::DCPS::getMinimalTypeIdentifier<OpenDDS::DCPS::Messengger_Message_xtag>();
}

const OpenDDS::XTypes::TypeMap& MessageTypeSupportImpl::getMinimalTypeMap() const
{
  return OpenDDS::DCPS::getMinimalTypeMap<OpenDDS::DCPS::Messengger_Message_xtag>();
}

const OpenDDS::XTypes::TypeIdentifier& MessageTypeSupportImpl::getCompleteTypeIdentifier() const
{
  return OpenDDS::DCPS::getCompleteTypeIdentifier<OpenDDS::DCPS::Messengger_Message_xtag>();
}

const OpenDDS::XTypes::TypeMap& MessageTypeSupportImpl::getCompleteTypeMap() const
{
  return OpenDDS::DCPS::getCompleteTypeMap<OpenDDS::DCPS::Messengger_Message_xtag>();
}

::DDS::ReturnCode_t MessageTypeSupportImpl::encode_to_string(const Message& in, CORBA::String_out out, OpenDDS::DCPS::RepresentationFormat* format)
{
#if OPENDDS_HAS_JSON_VALUE_WRITER
  OpenDDS::DCPS::JsonRepresentationFormat_var jrf = OpenDDS::DCPS::JsonRepresentationFormat::_narrow(format);
  if (jrf) {
    rapidjson::StringBuffer buffer;
    rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
    OpenDDS::DCPS::JsonValueWriter<rapidjson::Writer<rapidjson::StringBuffer> > jvw(writer);
    if (!vwrite(jvw, in)) {
      return ::DDS::RETCODE_ERROR;
    }
    out = buffer.GetString();
    return ::DDS::RETCODE_OK;
  }
#else
  ACE_UNUSED_ARG(in);
  ACE_UNUSED_ARG(format);
#endif
  out = "";
  return ::DDS::RETCODE_UNSUPPORTED;
}

::DDS::ReturnCode_t MessageTypeSupportImpl::encode_to_bytes(const Message& in, ::DDS::OctetSeq_out out, OpenDDS::DCPS::RepresentationFormat* format)
{
#if OPENDDS_HAS_JSON_VALUE_WRITER
  OpenDDS::DCPS::JsonRepresentationFormat_var jrf = OpenDDS::DCPS::JsonRepresentationFormat::_narrow(format);
  if (jrf) {
    CORBA::String_var buffer;
    const ::DDS::ReturnCode_t ret = encode_to_string(in, buffer, format);
    if (ret == ::DDS::RETCODE_OK) {
      const ::DDS::UInt32 len = static_cast< ::DDS::UInt32>(std::strlen(buffer));
      out = new ::DDS::OctetSeq(len);
      out->length(len);
      std::memcpy(out->get_buffer(), buffer, len);
      return ::DDS::RETCODE_OK;
    } else {
      out = new ::DDS::OctetSeq();
      return ret;
    }
  }
#else
  ACE_UNUSED_ARG(in);
  ACE_UNUSED_ARG(format);
#endif
  out = new ::DDS::OctetSeq();
  return ::DDS::RETCODE_UNSUPPORTED;
}

::DDS::ReturnCode_t MessageTypeSupportImpl::decode_from_string(const char* in, Message_out out, OpenDDS::DCPS::RepresentationFormat* format)
{
  out = new Message;
  OpenDDS::DCPS::set_default(*out);
#if OPENDDS_HAS_JSON_VALUE_READER
  OpenDDS::DCPS::JsonRepresentationFormat_var jrf = OpenDDS::DCPS::JsonRepresentationFormat::_narrow(format);
  if (jrf) {
    rapidjson::StringStream buffer(in);
    OpenDDS::DCPS::JsonValueReader<> jvr(buffer);
    return vread(jvr, *out) ? ::DDS::RETCODE_OK : ::DDS::RETCODE_ERROR;
  }
#else
  ACE_UNUSED_ARG(in);
  ACE_UNUSED_ARG(format);
#endif
  return ::DDS::RETCODE_UNSUPPORTED;
}

::DDS::ReturnCode_t MessageTypeSupportImpl::decode_from_bytes(const ::DDS::OctetSeq& in, Message_out out, OpenDDS::DCPS::RepresentationFormat* format)
{
#if OPENDDS_HAS_JSON_VALUE_READER
  OpenDDS::DCPS::JsonRepresentationFormat_var jrf = OpenDDS::DCPS::JsonRepresentationFormat::_narrow(format);
  if (jrf) {
    return decode_from_string(reinterpret_cast<const char*>(in.get_buffer()), out, format);
  }
#else
  ACE_UNUSED_ARG(in);
  ACE_UNUSED_ARG(format);
#endif
  out = new Message();
  return ::DDS::RETCODE_UNSUPPORTED;
}

MessageTypeSupport::_ptr_type MessageTypeSupportImpl::_narrow(CORBA::Object_ptr obj)
{
  return TypeSupportType::_narrow(obj);
}
}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<>
struct MetaStructImpl< ::Messengger::Message> : MetaStruct {
  typedef  ::Messengger::Message T;

#ifndef OPENDDS_NO_MULTI_TOPIC
  void* allocate() const { return new T; }

  void deallocate(void* stru) const { delete static_cast<T*>(stru); }

  size_t numDcpsKeys() const { return 0; }

#endif /* OPENDDS_NO_MULTI_TOPIC */

  Value getValue(const void* stru, const char* field) const
  {
    const ::Messengger::Message& typed = *static_cast<const ::Messengger::Message*>(stru);
    ACE_UNUSED_ARG(typed);
    if (std::strcmp(field, "sensor_id") == 0) {
      return typed.sensor_id;
    }
    if (std::strcmp(field, "sensor_name") == 0) {
      return typed.sensor_name.in();
    }
    if (std::strcmp(field, "temperature") == 0) {
      return typed.temperature;
    }
    if (std::strcmp(field, "humidity") == 0) {
      return typed.humidity;
    }
    if (std::strcmp(field, "pressure") == 0) {
      return typed.pressure;
    }
    if (std::strcmp(field, "light_intensity") == 0) {
      return typed.light_intensity;
    }
    if (std::strcmp(field, "timestamp") == 0) {
      return typed.timestamp;
    }
    if (std::strcmp(field, "location") == 0) {
      return typed.location.in();
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct ::Messengger::Message)");
  }

  Value getValue(Serializer& strm, const char* field, TypeSupportImpl* = 0) const
  {
    const Encoding& encoding = strm.encoding();
    ACE_UNUSED_ARG(encoding);
    size_t total_size = 0;
    if (encoding.xcdr_version() == Encoding::XCDR_VERSION_2) {
      if (!strm.read_delimiter(total_size)) {
        throw std::runtime_error("Unable to reader delimiter in getValue");
      }
    }
    std::string base_field = field;
    const size_t index = base_field.find('.');
    std::string subfield;
    if (index != std::string::npos) {
      subfield = base_field.substr(index + 1);
      base_field = base_field.substr(0, index);
    }
    if (base_field == "sensor_id") {
      ACE_CDR::Long val;
      if (!(strm >> val)) {
        throw std::runtime_error("Field 'sensor_id' could not be deserialized");
      }
      return val;
    } else {
      if (!strm.skip(1,  4 )) {
        throw std::runtime_error("Field 'sensor_id' could not be skipped");
      }
    }
    if (base_field == "sensor_name") {
      TAO::String_Manager val;
      if (!(strm >> val.out())) {
        throw std::runtime_error("Field 'sensor_name' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(strm >> len)) {
        throw std::runtime_error("String 'sensor_name' length could not be deserialized");
      }
      if (!strm.skip(len)) {
        throw std::runtime_error("String 'sensor_name' contents could not be skipped");
      }
    }
    if (base_field == "temperature") {
      ACE_CDR::Double val;
      if (!(strm >> val)) {
        throw std::runtime_error("Field 'temperature' could not be deserialized");
      }
      return val;
    } else {
      if (!strm.skip(1,  8 )) {
        throw std::runtime_error("Field 'temperature' could not be skipped");
      }
    }
    if (base_field == "humidity") {
      ACE_CDR::Double val;
      if (!(strm >> val)) {
        throw std::runtime_error("Field 'humidity' could not be deserialized");
      }
      return val;
    } else {
      if (!strm.skip(1,  8 )) {
        throw std::runtime_error("Field 'humidity' could not be skipped");
      }
    }
    if (base_field == "pressure") {
      ACE_CDR::Double val;
      if (!(strm >> val)) {
        throw std::runtime_error("Field 'pressure' could not be deserialized");
      }
      return val;
    } else {
      if (!strm.skip(1,  8 )) {
        throw std::runtime_error("Field 'pressure' could not be skipped");
      }
    }
    if (base_field == "light_intensity") {
      ACE_CDR::Double val;
      if (!(strm >> val)) {
        throw std::runtime_error("Field 'light_intensity' could not be deserialized");
      }
      return val;
    } else {
      if (!strm.skip(1,  8 )) {
        throw std::runtime_error("Field 'light_intensity' could not be skipped");
      }
    }
    if (base_field == "timestamp") {
      ACE_CDR::LongLong val;
      if (!(strm >> val)) {
        throw std::runtime_error("Field 'timestamp' could not be deserialized");
      }
      return val;
    } else {
      if (!strm.skip(1,  8 )) {
        throw std::runtime_error("Field 'timestamp' could not be skipped");
      }
    }
    if (base_field == "location") {
      TAO::String_Manager val;
      if (!(strm >> val.out())) {
        throw std::runtime_error("Field 'location' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(strm >> len)) {
        throw std::runtime_error("String 'location' length could not be deserialized");
      }
      if (!strm.skip(len)) {
        throw std::runtime_error("String 'location' contents could not be skipped");
      }
    }
    if (!field[0]) {
      return 0;
    }
    throw std::runtime_error("Did not find field in getValue");
  }

  ComparatorBase::Ptr create_qc_comparator(const char* field, ComparatorBase::Ptr next) const
  {
    ACE_UNUSED_ARG(next);
    if (std::strcmp(field, "sensor_id") == 0) {
      return make_field_cmp(&T::sensor_id, next);
    }
    if (std::strcmp(field, "sensor_name") == 0) {
      return make_field_cmp(&T::sensor_name, next);
    }
    if (std::strcmp(field, "temperature") == 0) {
      return make_field_cmp(&T::temperature, next);
    }
    if (std::strcmp(field, "humidity") == 0) {
      return make_field_cmp(&T::humidity, next);
    }
    if (std::strcmp(field, "pressure") == 0) {
      return make_field_cmp(&T::pressure, next);
    }
    if (std::strcmp(field, "light_intensity") == 0) {
      return make_field_cmp(&T::light_intensity, next);
    }
    if (std::strcmp(field, "timestamp") == 0) {
      return make_field_cmp(&T::timestamp, next);
    }
    if (std::strcmp(field, "location") == 0) {
      return make_field_cmp(&T::location, next);
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct ::Messengger::Message)");
  }

#ifndef OPENDDS_NO_MULTI_TOPIC
  const char** getFieldNames() const
  {
    static const char* names[] = {"sensor_id", "sensor_name", "temperature", "humidity", "pressure", "light_intensity", "timestamp", "location", 0};
    return names;
  }

  const void* getRawField(const void* stru, const char* field) const
  {
    if (std::strcmp(field, "sensor_id") == 0) {
      return &static_cast<const T*>(stru)->sensor_id;
    }
    if (std::strcmp(field, "sensor_name") == 0) {
      return &static_cast<const T*>(stru)->sensor_name;
    }
    if (std::strcmp(field, "temperature") == 0) {
      return &static_cast<const T*>(stru)->temperature;
    }
    if (std::strcmp(field, "humidity") == 0) {
      return &static_cast<const T*>(stru)->humidity;
    }
    if (std::strcmp(field, "pressure") == 0) {
      return &static_cast<const T*>(stru)->pressure;
    }
    if (std::strcmp(field, "light_intensity") == 0) {
      return &static_cast<const T*>(stru)->light_intensity;
    }
    if (std::strcmp(field, "timestamp") == 0) {
      return &static_cast<const T*>(stru)->timestamp;
    }
    if (std::strcmp(field, "location") == 0) {
      return &static_cast<const T*>(stru)->location;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct ::Messengger::Message)");
  }

  void assign(void* lhs, const char* field, const void* rhs,
    const char* rhsFieldSpec, const MetaStruct& rhsMeta) const
  {
    ACE_UNUSED_ARG(lhs);
    ACE_UNUSED_ARG(field);
    ACE_UNUSED_ARG(rhs);
    ACE_UNUSED_ARG(rhsFieldSpec);
    ACE_UNUSED_ARG(rhsMeta);
    if (std::strcmp(field, "sensor_id") == 0) {
      static_cast<T*>(lhs)->sensor_id = *static_cast<const  ::CORBA::Long*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "sensor_name") == 0) {
      static_cast<T*>(lhs)->sensor_name = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "temperature") == 0) {
      static_cast<T*>(lhs)->temperature = *static_cast<const  ::CORBA::Double*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "humidity") == 0) {
      static_cast<T*>(lhs)->humidity = *static_cast<const  ::CORBA::Double*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "pressure") == 0) {
      static_cast<T*>(lhs)->pressure = *static_cast<const  ::CORBA::Double*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "light_intensity") == 0) {
      static_cast<T*>(lhs)->light_intensity = *static_cast<const  ::CORBA::Double*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "timestamp") == 0) {
      static_cast<T*>(lhs)->timestamp = *static_cast<const  ::CORBA::LongLong*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "location") == 0) {
      static_cast<T*>(lhs)->location = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct ::Messengger::Message)");
  }

  bool compare(const void* lhs, const void* rhs, const char* field) const
  {
    ACE_UNUSED_ARG(lhs);
    ACE_UNUSED_ARG(field);
    ACE_UNUSED_ARG(rhs);
    if (std::strcmp(field, "sensor_id") == 0) {
      return static_cast<const T*>(lhs)->sensor_id == static_cast<const T*>(rhs)->sensor_id;
    }
    if (std::strcmp(field, "sensor_name") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->sensor_name.in(), static_cast<const T*>(rhs)->sensor_name.in());
    }
    if (std::strcmp(field, "temperature") == 0) {
      return static_cast<const T*>(lhs)->temperature == static_cast<const T*>(rhs)->temperature;
    }
    if (std::strcmp(field, "humidity") == 0) {
      return static_cast<const T*>(lhs)->humidity == static_cast<const T*>(rhs)->humidity;
    }
    if (std::strcmp(field, "pressure") == 0) {
      return static_cast<const T*>(lhs)->pressure == static_cast<const T*>(rhs)->pressure;
    }
    if (std::strcmp(field, "light_intensity") == 0) {
      return static_cast<const T*>(lhs)->light_intensity == static_cast<const T*>(rhs)->light_intensity;
    }
    if (std::strcmp(field, "timestamp") == 0) {
      return static_cast<const T*>(lhs)->timestamp == static_cast<const T*>(rhs)->timestamp;
    }
    if (std::strcmp(field, "location") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->location.in(), static_cast<const T*>(rhs)->location.in());
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct ::Messengger::Message)");
  }
#endif /* OPENDDS_NO_MULTI_TOPIC */

};

template<>
const MetaStruct& getMetaStruct< ::Messengger::Message>()
{
  static MetaStructImpl< ::Messengger::Message> msi;
  return msi;
}

bool gen_skip_over(Serializer& ser,  ::Messengger::Message*)
{
  ACE_UNUSED_ARG(ser);
  MetaStructImpl< ::Messengger::Message>().getValue(ser, "");
  return true;
}

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
#if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
template <>
class DynamicDataAdapterImpl< ::Messengger::Message,  ::Messengger::Message > : public DynamicDataAdapter_T< ::Messengger::Message> {
public:
  DynamicDataAdapterImpl(DDS::DynamicType_ptr type,  ::Messengger::Message& value)
    : DynamicDataAdapter_T< ::Messengger::Message>(type, value)
  {
  }

  DynamicDataAdapterImpl(DDS::DynamicType_ptr type, const  ::Messengger::Message& value)
    : DynamicDataAdapter_T< ::Messengger::Message>(type, value)
  {
  }

  DDS::ReturnCode_t clear_all_values()
  {
    const DDS::ReturnCode_t rc = assert_mutable("DynamicDataAdapter::clear_all_values");
    if (rc == DDS::RETCODE_OK) {
      OpenDDS::DCPS::set_default(value_);
    }
    return rc;
  }

  DDS::UInt32 get_item_count()
  {
    return 8;
  }

  bool serialized_size(const OpenDDS::DCPS::Encoding& enc, size_t& size, OpenDDS::DCPS::Sample::Extent ext) const
  {
    using namespace OpenDDS::DCPS;
    if (ext == Sample::Full) {
      DCPS::serialized_size(enc, size, value_);
    } else if (ext == Sample::NestedKeyOnly) {
      const NestedKeyOnly<const  ::Messengger::Message> nested_key_only(value_);
      DCPS::serialized_size(enc, size, nested_key_only);
    } else {
      KeyOnly<const  ::Messengger::Message> key_only(value_);
      DCPS::serialized_size(enc, size, key_only);
    }
    return true;
  }

  bool serialize(OpenDDS::DCPS::Serializer& ser, OpenDDS::DCPS::Sample::Extent ext) const
  {
    using namespace OpenDDS::DCPS;
    if (ext == Sample::Full) {
      return ser << value_;
    } else if (ext == Sample::NestedKeyOnly) {
      NestedKeyOnly<const  ::Messengger::Message> nested_key_only(value_);
      return ser << nested_key_only;
    } else {
      KeyOnly<const  ::Messengger::Message> key_only(value_);
      return ser << key_only;
    }
  }

protected:
  DDS::ReturnCode_t get_raw_value(const char* method, void* dest, DDS::TypeKind tk, DDS::MemberId id)
  {
    switch (id) {
    case 0:
      {
        return get_simple_raw_value(method, dest, tk, value_.sensor_id, id);
      }
    case 1:
      {
        return get_s8_raw_value(method, dest, tk, value_.sensor_name, id);
      }
    case 2:
      {
        return get_simple_raw_value(method, dest, tk, value_.temperature, id);
      }
    case 3:
      {
        return get_simple_raw_value(method, dest, tk, value_.humidity, id);
      }
    case 4:
      {
        return get_simple_raw_value(method, dest, tk, value_.pressure, id);
      }
    case 5:
      {
        return get_simple_raw_value(method, dest, tk, value_.light_intensity, id);
      }
    case 6:
      {
        return get_simple_raw_value(method, dest, tk, value_.timestamp, id);
      }
    case 7:
      {
        return get_s8_raw_value(method, dest, tk, value_.location, id);
      }
    default:
      return invalid_id(method, id);
    }
  }

  DDS::ReturnCode_t set_raw_value(const char* method, DDS::MemberId id, const void* source, DDS::TypeKind tk)
  {
    DDS::ReturnCode_t rc = assert_mutable(method);
    if (rc != DDS::RETCODE_OK) {
      return rc;
    }
    switch (id) {
    case 0:
      {
        return set_simple_raw_value(method, value_.sensor_id, id, source, tk);
      }
    case 1:
      {
        return set_s8_raw_value(method, value_.sensor_name.inout(), id, source, tk);
      }
    case 2:
      {
        return set_simple_raw_value(method, value_.temperature, id, source, tk);
      }
    case 3:
      {
        return set_simple_raw_value(method, value_.humidity, id, source, tk);
      }
    case 4:
      {
        return set_simple_raw_value(method, value_.pressure, id, source, tk);
      }
    case 5:
      {
        return set_simple_raw_value(method, value_.light_intensity, id, source, tk);
      }
    case 6:
      {
        return set_simple_raw_value(method, value_.timestamp, id, source, tk);
      }
    case 7:
      {
        return set_s8_raw_value(method, value_.location.inout(), id, source, tk);
      }
    default:
      return invalid_id(method, id);
    }
  }
};

#endif // if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Messengger::Message,  ::Messengger::Message>(DDS::DynamicType_ptr type, const  ::Messengger::Message& value)
{
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  if (type) {
    return new DynamicDataAdapterImpl< ::Messengger::Message,  ::Messengger::Message>(type, value);
  }
#  else
  ACE_UNUSED_ARG(type);
  ACE_UNUSED_ARG(value);
#  endif
  return 0;
}

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Messengger::Message,  ::Messengger::Message>(DDS::DynamicType_ptr type,  ::Messengger::Message& value)
{
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  if (type) {
    return new DynamicDataAdapterImpl< ::Messengger::Message,  ::Messengger::Message>(type, value);
  }
#  else
  ACE_UNUSED_ARG(type);
  ACE_UNUSED_ARG(value);
#  endif
  return 0;
}

template <>
const  ::Messengger::Message* get_dynamic_data_adapter_value< ::Messengger::Message,  ::Messengger::Message>(DDS::DynamicData_ptr dd)
{
  ACE_UNUSED_ARG(dd);
#  if OPENDDS_HAS_DYNAMIC_DATA_ADAPTER
  typedef DynamicDataAdapterImpl< ::Messengger::Message,  ::Messengger::Message> Dda;
  const Dda* const dda = dynamic_cast<Dda*>(dd);
  if (dda) {
    return &dda->wrapped();
  }
#  endif
  return 0;
}
#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: Message */

/* End MODULE: Messengger */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

namespace {
XTypes::TypeObject OPENDDS_IDL_FILE_SPECIFIC(minimal_to, 0)()
{
  static const unsigned char to_bytes[] = { 148, 0, 0, 0, 241, 81, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 132, 0, 0, 0, 8, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 1, 0, 4, 217, 109, 134, 106, 0, 12, 0, 0, 0, 1, 0, 0, 0, 1, 0, 112, 0, 46, 72, 121, 241, 11, 0, 0, 0, 2, 0, 0, 0, 1, 0, 10, 238, 244, 56, 247, 0, 11, 0, 0, 0, 3, 0, 0, 0, 1, 0, 10, 67, 170, 17, 208, 0, 11, 0, 0, 0, 4, 0, 0, 0, 1, 0, 10, 217, 159, 173, 150, 0, 11, 0, 0, 0, 5, 0, 0, 0, 1, 0, 10, 183, 57, 152, 64, 0, 11, 0, 0, 0, 6, 0, 0, 0, 1, 0, 5, 215, 230, 213, 91, 0, 12, 0, 0, 0, 7, 0, 0, 0, 1, 0, 112, 0, 213, 24, 157, 224  };
  XTypes::TypeObject to;
  if (!to_type_object(to_bytes, sizeof(to_bytes), to)) {
    throw std::runtime_error("Could not deserialize minimal Type Object 0");
  }
  return to;
}

XTypes::TypeMap OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map_private, 0)()
{
  XTypes::TypeMap tm;
  tm[XTypes::TypeIdentifier(XTypes::EK_MINIMAL, XTypes::EquivalenceHashWrapper(21, 42, 3, 79, 102, 114, 218, 239, 105, 167, 227, 124, 201, 240))] = OPENDDS_IDL_FILE_SPECIFIC(minimal_to, 0)();
  return tm;
}

XTypes::TypeObject OPENDDS_IDL_FILE_SPECIFIC(complete_to, 0)()
{
  const unsigned char to_bytes[] = {
27, 1, 0, 0, 242, 81, 2, 0, 28, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 77, 101, 115, 115, 101, 110, 103, 103, 101, 114, 58, 58, 77, 101, 115, 115, 97, 103, 101, 0, 243, 0, 0, 0, 8, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 1, 0, 4, 0, 10, 0, 0, 0, 115, 101, 110, 115, 111, 114, 95, 105, 100, 0, 0, 0, 26, 0, 0, 0, 1, 0, 0, 0, 1, 0, 112, 0, 12, 0, 0, 0, 115, 101, 110, 115, 111, 114, 95, 110, 97, 109, 101, 0, 0, 0, 0, 0, 26, 0, 0, 0, 2, 0, 0, 0, 1, 0, 10, 0, 12, 0, 0, 0, 116, 101, 109, 112, 101, 114, 97, 116, 117, 114, 101, 0, 0, 0, 0, 0, 23, 0, 0, 0, 3, 0, 0, 0, 1, 0, 10, 0, 9, 0, 0, 0, 104, 117, 109, 105, 100, 105, 116, 121, 0, 0, 0, 0, 23, 0, 0, 0, 4, 0, 0, 0, 1, 0, 10, 0, 9, 0, 0, 0, 112, 114, 101, 115, 115, 117, 114, 101, 0, 0, 0, 0, 30, 0, 0, 0, 5, 0, 0, 0, 1, 0, 10, 0, 16, 0, 0, 0, 108, 105, 103, 104, 116, 95, 105, 110, 116, 101, 110, 115, 105, 116, 121, 0, 0, 0, 0, 0, 24, 0, 0, 0, 6, 0, 0, 0, 1, 0, 5, 0, 10, 0, 0, 0, 116, 105, 109, 101, 115, 116, 97, 109, 112, 0, 0, 0, 23, 0, 0, 0, 7, 0, 0, 0, 1, 0, 112, 0, 9, 0, 0, 0, 108, 111, 99, 97, 116, 105, 111, 110, 0, 0, 0  };
  XTypes::TypeObject to;
  if (!to_type_object(to_bytes, sizeof(to_bytes), to)) {
    throw std::runtime_error("Could not deserialize complete Type Object 0");
  }
  return to;
}

XTypes::TypeMap OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map_private, 0)()
{
  XTypes::TypeMap tm;
  tm[XTypes::TypeIdentifier(XTypes::EK_COMPLETE, XTypes::EquivalenceHashWrapper(3, 125, 222, 30, 113, 7, 154, 203, 17, 121, 124, 49, 17, 248))] = OPENDDS_IDL_FILE_SPECIFIC(complete_to, 0)();
  return tm;
}
}

const XTypes::TypeMap& OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map, 0)()
{
  static XTypes::TypeMap tm;
  ACE_GUARD_RETURN(ACE_Thread_Mutex, guard, TheServiceParticipant->get_static_xtypes_lock(), tm);
  if (tm.empty()) {
    tm = OPENDDS_IDL_FILE_SPECIFIC(get_minimal_type_map_private, 0)();
  }
  return tm;
}

const XTypes::TypeMap& OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map, 0)()
{
  static XTypes::TypeMap tm;
  ACE_GUARD_RETURN(ACE_Thread_Mutex, guard, TheServiceParticipant->get_static_xtypes_lock(), tm);
  if (tm.empty()) {
    tm = OPENDDS_IDL_FILE_SPECIFIC(get_complete_type_map_private, 0)();
  }
  return tm;
}
} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

